server:
  port: ${PORT:8192}
spring:
  application:
    name: customer-service

eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://127.0.0.1:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    
ribbon:
  eureka:
    enabled: true