server:
  port: ${PORT:8192}
  servlet:
    context-path: /customer
spring:
  application:
    name: mtm-customer-service
  zipkin:
    baseUrl: ${ZIPKIN_URL:http://localhost:9411}
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - x-request-id
      correlation:
        fields:
          - x-request-id

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    disable-swagger-default-url: true
    url: /customer/v3/api-docs
    config-url: /customer/v3/api-docs/swagger-config
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: 
    - /api/**
    - /actuator/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      customerService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://127.0.0.1:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true