server:
  port: 8196
  servlet:
    context-path: /graphql

spring:
  application:
    name: mtm-graphql-service
  datasource:
    url: jdbc:h2:mem:graphqldb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    disable-swagger-default-url: true
    url: /graphql/v3/api-docs
    config-url: /graphql/v3/api-docs/swagger-config
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: 
    - /api/**
    - /actuator/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    org.springframework: INFO
    com.mtm.examples: DEBUG 