server:
  port: ${PORT:8191}
spring:
  application:
    name: mtm-account-service
  zipkin:
    baseUrl: ${ZIPKIN_URL:http://localhost:9411}
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - x-request-id
      correlation:
        fields:
          - x-request-id

management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://127.0.0.1:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true