server:
  port: ${PORT:8191}
  servlet:
    context-path: /account
spring:
  application:
    name: mtm-account-service
  zipkin:
    baseUrl: ${ZIPKIN_URL:http://localhost:9411}
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - x-request-id
      correlation:
        fields:
          - x-request-id

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    disable-swagger-default-url: true
    url: /account/v3/api-docs
    config-url: /account/v3/api-docs/swagger-config
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: 
    - /api/**
    - /actuator/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://127.0.0.1:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true