info:
  component: Edge Server
  
management:
  endpoint:
    shutdown:
      enabled: true
    restart:
      enabled: true
    health:
      enabled: false
      
zuul:
  prefix: /api
  routes:
    account: 
      path: /account/**
      serviceId: account-service
    customer: 
      path: /customer/**
      serviceId: customer-service          

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://127.0.0.1:8761}/eureka/
    registerWithEureka: false
      
server:
  port: 8762

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG