spring:
  application:
    name: MTM Spring Boot Examples
  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8191

sample:
  baseurl: http://localhost:8080/
  baseUrl2: http://localhost:8081/

